FROM python:3.8
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9
ENV TERM xterm

RUN apt-get update && apt-get install --no-install-recommends -y \
    curl && \
    apt-get clean
RUN apt-get install -y libgl1-mesa-dev \
                    libusb-1.0-0

RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

RUN apt-get install -y cabextract libfontenc1 libmspack0 xfonts-encodings xfonts-utils
RUN wget http://ftp.jp.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.8_all.deb
RUN dpkg -i ttf-mscorefonts-installer_3.8_all.deb
RUN rm ttf-mscorefonts-installer_3.8_all.deb

ADD requirements_for_jupyter.txt ./
RUN python -m pip install --upgrade pip
RUN pip install -r requirements_for_jupyter.txt
RUN pip install --upgrade matplotlib